### ISSUE TITLE
duplicate because tasks are recreated after sync

### ISSUE THREAD

**Issue by svengeboers** [tools-life/taskwiki#417]
Hi, thanks developing this software first of all, it's great!

I have a weird issue and I'm not sure whether it is a bug or a feature, and what I should do to fix it. I found some posts that looked like they had similar issues/situations but not exactly the same.

Basically: I use taskwarrior in combination with foreground on android. The "bug" is as follows:
1. I create a task on my laptop, and it shows in vimwiki when I open vimwiki
2. I do task sync on my laptop
3. I do task sync on my phone
4. I mark the task as being done, on my phone
5. I do task sync again on my phone
6. I do task sync on my laptop, now the task shows up in taskwarrior as being completed
_7. At this point, vimwiki is still pending and the task still shows up as incompleted, when I then close vimwiki (:wq), the task is again changed from completed, to pending, whilst it is already completed._

Is this intended behaviour? _Is there a reason why it is not first checked whether a task has been marked from pending to comleted?_ Is there a recommended workflow that circumvents the behaviour?

I both use my laptop and phone quite often to check of tasks, so this "bug" results in quite a bit of duplicate tasks (that is: the same task showing up again and requiring being checked off again).

Greetings,
S

**Comment by liskin** [comment]
I'd say it's almost a feature. If I understand correctly, your issue is that tasks in a running vim instance don't automatically update when you sync in the background, and there is indeed no code in taskwiki that would trigger an automatic refresh.

That being said, as someone who uses taskwiki a lot I hacked together a refresh logic tailored to my workflows:
* https://github.com/liskin/dotfiles/blob/home/.vim/after/ftplugin/vimwiki/liskin.vim#L19-L25
* https://github.com/liskin/dotfiles/blob/home/.vim/autoload/vimwiki/liskin.vim#L15-L31
What it does it checks whether a refresh is needed every time I focus vim (needs terminal with focus reporting) or change window/buffer inside of vim. To check whether to refresh, it compares mtime of taskwarrior data files with the mtime of the current wiki file, and also forces a refresh once a day because I use "today"/"tomorrow" viewports that need to be updated every day.

I never tried to upstream this because getting focus reporting working wasn't trivial at the time I wrote this, and also the "refresh once a day" logic is specific to my usecase.
